CREATE DATABASE HELPDESK_PRO;

CREATE TABLE usuarios(
    ID_USUARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TIPO ENUM('user','admin') NOT NULL DEFAULT 'user',
    CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chamados(
    ID_CHAMADO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    PRIORIDADE ENUM('baixa','media','alta','urgente') NOT NULL,
    STATUS_CHAMADO ENUM('aberto','andamento','fechado') NOT NULL DEFAULT 'aberto',
    USUARIO_ID INT NOT NULL,
    ADMIN_ID INT,
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY(ADMIN_ID) REFERENCES USUARIOS(ID_USUARIO) ON DELETE SET NULL,
    CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE INTERACAO(
    ID_INTERACAO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    CHAMADO_ID INT NOT NULL,
    MENSAGEM TEXT NOT NULL,
    FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY(CHAMADO_ID) REFERENCES CHAMADOS(ID_CHAMADO) ON DELETE CASCADE,
    CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);